language: java
sudo: false
jdk:
- oraclejdk7
script:
- echo "Travis branch is $TRAVIS_BRANCH"
- echo "Travis branch is in pull request? $TRAVIS_PULL_REQUEST"
- echo "Travis tag $TRAVIS_TAG"
- gradle test publish --continue
notifications:
  email:
  - toxicbakery@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_ea430154e177_key -iv $encrypted_ea430154e177_iv
  -in maven.keystore.gpg.enc -out maven.keystore.gpg -d
